name: Java CI with Maven

on:
  push:
    branches: [main, develop, pipeline-*]
  pull_request:
    branches: [main, develop, pipeline-*]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE
      - name: Set up JDK 19
        uses: actions/setup-java@v4 # Sets up a Java Development Kit (JDK)
        with:
          java-version: "19"
          distribution: "temurin"
          cache: "maven" # Caches Maven dependencies to speed up subsequent builds
      - name: Build, test and coverage check
        run: mvn -B clean verify
      - name: publish  JaCoCo report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/jacoco-report/
      - name: publish  JUnit report
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/
      - name: Build with Maven
        run: mvn install # Executes the Maven build command
      - name: Run tests
        run: mvn test # Executes Maven tests
