name: SonarQube Analysis

on:
  push:
    branches: [main, develop, pipeline-*]
  pull_request:
    branches: [main, develop, pipeline-*]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONNAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=my-java-project
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.java.binaries=target/classes
            -Dsonar.java.test.binaries=target/test-classes
            -Dsonar.junit.reportsPath=target/surefire-reports
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.qualitygate.wait=true # Wait for quality gate status
